name 'puppet'
maintainer 'David A. Lane'
maintainer_email 'david.lane@gdit.com'
license 'all_rights'
description 'Installs/Configures puppet'
long_description 'Installs/Configures puppet'
version '0.1.0'
